version: "3.8"

services:
  db:
    image: "postgres:16-alpine"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: interludes
    ports:
      - "5435:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
